### ISSUE TITLE
Third-person spectator camera doesn't follow launched TV missiles

### ISSUE THREAD

**Issue by OrfeasZ** [VeniceUnleashed/VeniceUnleashed#140]

**Comment by OrfeasZ** [comment]
This also appears to happen for EOD bots and MAVs.

**Comment by derrod** [comment]
In that case it's probably not working correctly for all vehicles spawned using the VehicleProjectile.

But it should be irrelevant for all the others, you can't enter the TUGS or Radio Beacon. Only the M224 (Mortar) should be affected by this, but it doesn't really matter since the soldier remains close to the "Vehicle" and the difference is probably minimal.

That said, maybe you can force the camera to follow a vehicle that has a RemoteEntry when it's spawned by a player? I'm not sure about the details but that sounds like a workaround if possible.

**Comment by FlashHit** [comment]
Is this still a VU issue? 🤔

**Comment by FlashHit** [comment]
moved it to https://github.com/EmulatorNexus/VU-Spec/issues/3
