### ISSUE TITLE
Application deletes after launching... 

### ISSUE THREAD

**Issue by Noobasoar** [VeniceUnleashed/VeniceUnleashed#181]
Good day

Today I have tried to start Venice Unleashed, but then it pops up with a windows error and the application deletes itself... Any suggestions?

The error reads... Windows cannot access the specified device, path, or file.  You may not have the appropriate permissions to access them. 

What is weird is that it has worked fine the previous couple of days and now it deletes itself from my system....???

**Comment by Xulunix** [comment]
VU is currently detected as false positive by many anti-virus solutions.
Try to whitelist the folder of VU in your AV and reinstall Venice.

**Comment by OrfeasZ** [comment]
As detailed in our downloads page:
The nature of the Venice Unleashed launcher can (and will) cause it to be falsely identified as a virus by various different Anti-Virus solutions. We are currently in the process of submitting samples to Anti-Virus vendors in order to eliminate this issue, but until then you might have to add Venice Unleashed to the exception list of your Anti-Virus.
