### ISSUE TITLE
Norton blocks installation and files

### ISSUE THREAD

**Issue by jasonkesler** [VeniceUnleashed/VeniceUnleashed#187]
Please submit your program to Norton so it will not be blocked in the future.

**Comment by MizuDG** [comment]
The devs said they're already working on submitting samples. http://veniceunleashed.net/downloads

 In the meantime, add it to your exception list.

**Comment by OrfeasZ** [comment]
As detailed in our downloads page:
The nature of the Venice Unleashed launcher can (and will) cause it to be falsely identified as a virus by various different Anti-Virus solutions. We are currently in the process of submitting samples to Anti-Virus vendors in order to eliminate this issue, but until then you might have to add Venice Unleashed to the exception list of your Anti-Virus.
