### ISSUE TITLE
How do i start create custom mods in Venice Unleashed?

### ISSUE THREAD

**Issue by judemvm** [VeniceUnleashed/VeniceUnleashed#216]
How do i start create custom mods in Venice Unleashed? Rime not supported FB2 in Battlefield 3.
[http://blog.nofate.me/?p=153](http://blog.nofate.me/?p=153)
 [http://blog.nofate.me/?p=166](http://blog.nofate.me/?p=166)
[http://forums.veniceunleashed.net/viewtopic.php?f=39&t=5979](http://forums.veniceunleashed.net/viewtopic.php?f=39&t=5979)
[http://forums.veniceunleashed.net/viewtopic.php?f=39&t=6391](http://forums.veniceunleashed.net/viewtopic.php?f=39&t=6391)

**Comment by kiwidoggie** [comment]
I have uploaded a small notes dump on the basics of VeniceEXT. As VeniceEXT is still under development, this is due to change at any point and is only for the current build of Venice Unleashed at the time of this writing. As for Rime, it is still in heavy development and is around 80% complete (without plugin development)

https://github.com/EmulatorNexus/VeniceEXT-tutorial

This is all for now until the final documentation comes out with the mod tools.
