### ISSUE TITLE
Accessing name or typeName of UnlockAsset crashes server in some maps

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#241]
Working map example: XP2_Skybar TeamDeathMatchC0 2
Not working map example: MP_Subway ConquestLarge0 2

UnlockAsset.name or UnlockAsset.typeName crashes the server on some maps. UnlockAsset.debugUnlockId works, but when printing its value sometimes prints random characters on those maps.
[test.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1406919/test.zip)

**Comment by OrfeasZ** [comment]
Fixed in build 12229

**Comment by FoolHen** [comment]
Still same problem with MP_Subway ConquestLarge0 2 using that same mod. (Btw, updated test.zip as it had a semicolon at the end of the json file)

**Comment by OrfeasZ** [comment]
This is fixed in build 12374. This is a special case of instances where some fields that are references to other instances are very lazy-loaded by the engine, and therefore require a more complex access path. In this case, upon initial load, `unlockAsset` for some of the members of the array will return `nil` as the referenced instance will not have been loaded yet. If you keep the instance reference around and check it at a later time the fields **should** be populated.
