### ISSUE TITLE
config.json like system for mod configurations.

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#247]
Each mod should have access to a config file that's located somewhere in the server directory. With an easily accessable key getter/setter.

Eg. TestMod should have read/write access to Server/Configuration/testmod.json.

```
Testmod.json:
{
    "JumpHeight": "10",
    "SprintSpeed": "5"
}
```
```
mod.lua:
local s_JumpHeight = ConfigurationManager:GetValue('JumpHeight')
if(s_JumpHeight == nil) then
    ConfigurationManager:SetKey('JumpHeight, 10)
end
s_Instance.jumpHeight = ConfigurationManager:GetValue('JumpHeight')

```
This is not to be confused with an database-like system as discussed before.

It's intended to be used as a way to store mod configurations without having to modify the mods directly, allowing the server host to update mods safely without having to redo configuration changes.

Edit:

Keys and values should be writeable from the mod, allowing the mod to add additional configuration lines in case of an update.

**Comment by OrfeasZ** [comment]
Build `13911` adds server-side SQLite support to VEXT. A new `SQL` library has been introduced with the following methods:

- `bool SQL:Open()`: Opens a connection to the database if one has not already been opened. The database is stored in `Mods/mod-name/mod.db`.
- `void SQL:Close()`: Closes the active connection to the database.
- `table SQL:Query(string query, args...)`: Executes an SQL `query` with the specified bound arguments. Returns a table of rows if successful, otherwise `false`.
- `string SQL:Escape(string text)`: Escapes a string for usage in an SQL query. This is not necessary when binding arguments directly using the `SQL:Query(...)` method.
- `string SQL:Error()`: Returns a description of the last error that occurred.
- `int SQL:AffectedRows()`: Returns the number of rows the last successful query affected.
- `int SQL:LastInsertID()`: Returns the ID of the most recently inserted row.
- `SQLBlob SQL:Blob(string data)`: Returns an `SQLBlob` object for use in queries.

Example usage:
```lua
function SQLExample()
    if not SQL:Open() then
        return
    end

    -- Create our table.
    local query = [[
        CREATE TABLE IF NOT EXISTS test_table (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            text_value TEXT,
            int_value INTEGER,
            real_value REAL,
            blob_value BLOB,
            some_null_value BLOB,
            not_null_text TEXT NOT NULL
        )
    ]]

    if not SQL:Query(query) then
        print('Failed to execute query: ' .. SQL:Error())
        return
    end

    -- Insert some test data.
    query = 'INSERT INTO test_table (text_value, int_value, real_value, blob_value, some_null_value, not_null_text) VALUES (?, ?, ?, ?, ?, ?)'

    if not SQL:Query(query, 'My Text', 1337, 420.69, SQL:Blob('My Blob'), nil, 'My Not Null Text') then
        print('Failed to execute query: ' .. SQL:Error())
        return
    end

    if not SQL:Query(query, 'My Text 2', 13372, 420.692, SQL:Blob('My Blob 2'), nil, 'My Not Null Text 2') then
        print('Failed to execute query: ' .. SQL:Error())
        return
    end

    print('Inserted data. Insert ID: ' .. tostring(SQL:LastInsertID()) .. '. Rows affected: ' .. tostring(SQL:AffectedRows()))

    -- Test the NOT NULL constraint.
    if not SQL:Query(query, 'My Text', 1337, 420.69, SQL:Blob('My Blob'), nil, nil) then
        -- Error should be "NOT NULL constraint failed: test_table.not_null_text"
        print('Failed to execute query: ' .. SQL:Error())
    end

    -- Fetch all rows from the table.
    results = SQL:Query('SELECT * FROM test_table')

    if not results then
        print('Failed to execute query: ' .. SQL:Error())
        return
    end

    -- Print the fetched rows.
    for _, row in pairs(results) do
        print('Got row:')
        print(row)
    end
end
```
