### ISSUE TITLE
[Crash] Crash when starting VU server with a DLC map without having that DLC installed

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#270]
Server crashes when checking for client updates.
Doesn't matter if a mod loaded or not.

Crashdump:
[CrashdumpVUServerStartupCrash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1627135/CrashdumpVUServerStartupCrash.zip)

**Comment by 3ti65** [comment]
Cause of this particular crash was starting up a map of a DLC that was missing.
A dedicated error message should be prompted informing the user of him lacking the DLC.

Possibly also implement a way for the mod.json file to list DLCs needed to work with them.

**Comment by OrfeasZ** [comment]
Build `14724` fixes crashes caused by loading DLC levels that don't exist. Instead, the server will now fall back to the default level (usually `MP_Subway`). 

Build `14724` also adds a new `SharedUtils` method: `SharedUtils:GetContentPackages()`. This method returns all currently available content (DLC) packages as a table of strings. Keep in mind that this function will only return the available packages after the first settings bundle has been read and has been fully mounted.

**Comment by OrfeasZ** [comment]
Keep in mind that this still won't guard you against incomplete, half-downloaded, or otherwise corrupt game installations.
