### ISSUE TITLE
[Bug] Client disconnect when server really busy?

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#274]
Issue:

In my mod i read all ObjectBlueprints and put them in a list. When i then sort the list the client disconnects while the server is busy printing out stuff. Might be related to the print / console output. Or is this due to server overload? No kick message whatsoever.

Testmod:

[xulumod.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1649855/xulumod.zip)

Steps to reproduce:

- Type in chat: 'objects'
- Watch server console, it's spitting out the objectblueprint names alphabetically
-> Client disconnects in 2 out of 3 times roughly

Might be some timeout set very low or something.

**Comment by Powback** [comment]
How long does it take to print? I would guess that the client console is busy, the server doesn’t receive a response and kicks the player as a response.

**Comment by 3ti65** [comment]
It's the server console though, shouldn't be related to the player directly.

**Comment by Powback** [comment]
So if the player doesn’t respond the client disconnects then. Should take a few secs though

**Comment by 3ti65** [comment]
It feels like roughly 3-5 seconds. Should be configurable probably. Like picture 100 people losing connection because the server times out for 5 seconds.

**Comment by OrfeasZ** [comment]
The connection between the client and the server times out after approximately 7 seconds in the worst case (iirc). If a keep-alive isn't sent in that period (ie. because of the server being super busy and unable to process a tick) then the client will get disconnected.

If you want to process a large amount of data you should instead do it incrementally on each tick (ie. `Engine:Update` event).
