### ISSUE TITLE
[Crash] Crash when applying enough damage to a soldier to kill him

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#322]
Using s_Soldier:ApplyDamage(damageInfo), the server crashes when applying enough damage to kill a soldier. Setting player.soldier.health to 0 works fine however.

Crashdump:
[applydamage crashdump.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2070225/applydamage.crashdump.zip)

Testmod:
[HealthSystem.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2431776/HealthSystem.zip)

Steps to reproduce:

1. spawn in, type "test" -> player gets 99 damage applied
2. wait 4 seconds (theres an automated bleed out in the background)
3. server crashes

Steps that should do the same but dont crash:

1. spawn in, type "99" -> player health gets set to 99, no automated bleed out
2. type "test" -> player gets 99 damage applied -> dies
3. no crash

**Comment by OrfeasZ** [comment]
This seems to be caused by some weird heap corruption issue that occurs when killing a player in the main update loop. The latest build (13187+) introduces a new event `UpdateManager:Update` with two parameters: `deltaTime` and `pass` (`UpdatePass` enum) that can be used to avoid this issue until a more permanent solution is found. If you kill a player during the `UpdatePass_PreSim` pass you shouldn't have any issues.

**Comment by 3ti65** [comment]
The workaround with the UpdatePass_PreSim works well.

**Comment by 3ti65** [comment]
Still crashes with 13738.

Updated testmod.

**Comment by FoolHen** [comment]
For future reference, this is fixed. UpdatePass_PreSim workaround isn't needed anymore.
