### ISSUE TITLE
[Crash] Client crashes when you close the server

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#353]
Happens with latest RM version. Might not be related to the mod though. Even if you're disconnected from the server, but you've been on it, your client will still crash if the server then closes. #wtf

Crashdump:

[ClosingServerClientCrash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2359028/ClosingServerClientCrash.zip)

**Comment by iKiWY** [comment]
yea its fuked

**Comment by FoolHen** [comment]
Might be caused by hooks, if a mod doesn't have a hook it wont close. At least in my experience, just a theory.

**Comment by OrfeasZ** [comment]
This looks like a timing issue with the same root cause as #354, where your client has started disconnecting from the server but said disconnection hasn't fully finished (ie. a monitored harmony connection is still active). As soon as the server closes and the mHarmony connection gets dropped, your client unloads all VeniceEXT modules, which in turn try to destroy data that's already been destroyed (because the level has already unloaded) which results in the crash you're experiencing.

I'll add some extra checks to disconnect the player fully whenever an fb socket disconnection happens, which should also resolve #354.

**Comment by OrfeasZ** [comment]
Build `13512` adds additional checks for #354 and also makes the `Level:Destroy` event available on clients, which you can use to clean up any resources.

**Comment by FoolHen** [comment]
This is still happening for me.
