### ISSUE TITLE
[Crash] Modifying instances on client cause a crash.

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#360]
If you modify instances on client, the client crashes when you leave / the server closes. This only happens if the round is restarted. Note that this also happens with other instances, not just with the one in the testmod.
Testmod: 
[test.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2453865/test.zip)
Crash dump:
[1b166f47-8e41-432d-b274-78273809edab.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2453867/1b166f47-8e41-432d-b274-78273809edab.zip)
Map: ``XP3_Shield ConquestLarge0 2``

**Comment by Powback** [comment]
Could this be related to #344 somehow?

**Comment by OrfeasZ** [comment]
This is caused because of DC lifecycle management issues. Calling `collectgarbage()` on `Level:Destroy` fixes this. Just as a general precaution, build `14032` forces garbage collection on each VEXT module right after the `Level:Destroy` event is called, and also introduces an `ExtensionUnloading` event which can be used to clean things up right before an extension is about to unload (eg. when reloading extensions or when the server connection gets dropped and VEXT is unloaded before the client has unloaded the level).
