### ISSUE TITLE
[Crash] Silent client crash when spawning entity

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#419]
[KitSpawn.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/2895563/KitSpawn.zip)

1. type in 'kit' in the chat after spawning
2. client shits itself

**Comment by OrfeasZ** [comment]
@3ti65 does this still result in a silent crash in latest?

**Comment by OrfeasZ** [comment]
This should no longer crash silently in build `15095`.

**Comment by 3ti65** [comment]
Shit forgot to check. Will test it though.

**Comment by FoolHen** [comment]
Now it creates a [dump](https://github.com/EmulatorNexus/VeniceUnleashed/files/3356476/7ce932c9-af6b-4425-b71f-3236b186dcd3.zip).

**Comment by OrfeasZ** [comment]
This crashes because the networked `WeaponUnlockPickupEntity` tries to look up its entity data on the client, but that entity data doesn't exist. You'd probably have to a `PrefabBlueprint` (or something like that) on level load, create your entity data, add it to it, and register the prefab in the level registry with a unique blueprint index.

**Comment by OrfeasZ** [comment]
Keep in mind that this is probably the case for every networked entity. For example, if you create your own VehicleEntityData without registering it and then try to spawn the vehicle it'll probably crash too.

**Comment by Powback** [comment]
@OrfeasZ Do you know how the entity data is looked up? Is it enough to register the custom instance to a new partition? Would it be the same data argument that's assumingly passed to ClientEntityFactory:Create ?

**Comment by OrfeasZ** [comment]
It's based on `IndexInBlueprint` and relevant fields as far as I know.
