### ISSUE TITLE
[Req] Add a way to tell gunsways apart in GunSway:UpdateRecoil

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#436]
For our custom recoil logic we need to know for which weapon the gunsway is, and as ``soldierWeapon`` argument seems to be nil for every weapon except the local one we cant differentiate gunsways of other players' weapons. A weapon id param would be sufficient.

**Comment by OrfeasZ** [comment]
Build `14805` adds a new shared `WeaponFiring` type with the following fields:

- `DataContainer data`
- `DataContainer firingHolderData`
- `GunSway gunSway`
- `Entity soldierWeapon`
- `WeaponState weaponState`
- `WeaponState lastWeaponState`
- `WeaponState nextWeaponState`
- `float switchCooldownTimer`
- `float autoReplenishTime`
- `float timeToWait`
- `float holdReleaseMinDelay`
- `float recoilTimer`
- `float recoilAngleX`
- `float recoilAngleY`
- `float recoilAngleZ`
- `float recoilFovAngle`
- `float primaryAmmoReplenishDelay`
- `float reloadTimeMultiplier`
- `float overheatDropMultiplier`
- `int primaryAmmoToFill`
- `int instanceID`

All fields are writable except for `data`, `gunSway`, and `soldierWeapon`. 

`WeaponState` is an enum that has the following values:

- `Deploy`
- `AltDeploy`
- `TriggerReleaseWait`
- `NoTrigger`
- `PreFireDelay`
- `PrimarySingleDelay`
- `PrimarySingle`
- `BoltActionDelay`
- `BoltAction`
- `PrimaryAutomaticFire`
- `ReloadDelay`
- `PostReload`
- `PrimaryHoldAndRelease_Hold`
- `PrimaryHoldAndRelease_ReleaseDelay`
- `PrimaryHoldAndRelease_Release`
- `NumWeaponStates`

The client `SoldierWeapon` type has been modified and the `correctedGunSway` and `predictedGunSway` fields have been removed. Two new fields have been added:

- `WeaponFiring correctedWeaponFiring`
- `WeaponFiring predictedWeaponFiring`

The `GunSway:Update` and `GunSway:UpdateRecoil` events have been updated to receive a `WeaponFiring` object instead of a the `SoldierWeapon` entity.

The following new events have been added:

- `WeaponFiring:Create(WeaponFiring weaponFiring)`
- `WeaponFiring:Update(WeaponFiring weaponFiring)`

**Comment by OrfeasZ** [comment]
Build `14818` changes the gunsway update events even further. They now look like this:

- `GunSway:Update(GunSway gunSway, Entity soldierWeapon, WeaponFiring weaponFiring, float deltaTime)`
- `GunSway:UpdateRecoil(GunSway gunSway, Entity soldierWeapon, WeaponFiring weaponFiring, float deltaTime)`

The `soldierWeapon` `Entity` should be present for all players, on both server and client. `weaponFiring` should be present for all players on the server and only the local player on the client.
