### ISSUE TITLE
[Req] Hooks for nametags and killfeed

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#441]
As discussed, add hooks that allow control over natively rendered elements, such as the nametags and the part of the killfeed.
Would probably be good to be able to fully disable the natively rendered stuff.

**Comment by 3ti65** [comment]
yo this probably includes the reticles for the scopes and red dots, because i cant find them anywhere in the ebx

**Comment by OrfeasZ** [comment]
Build `14945` adds the following new hooks:

- `void UI:DrawEnemyNametag()`
- `void UI;DrawFriendlyNametag()`
- `void UI:DrawSquadNametag()`
- `void UI:DrawNametags()`
- `void UI:DrawMoreNametags()`
- `void UI:UpdateNametagIcons()`
- `bool UI:NametagsShouldUpdate()`
- `void UI:CreateKillMessage()`
- `void UI:RenderMinimap()`

If you want to completely disable nametag rendering you should install hooks for `UI:DrawNametags`, `UI:DrawMoreNametags`, `UI:UpdateNametagIcons` and `UI:NametagsShouldUpdate` and return immediately in them (for the `UI:NametagsShouldUpdate` hook you should return `false`). Otherwise, you can selectively control rendering behavior by hooking the friendly/enemy/squad variants.
