### ISSUE TITLE
Visual glitches when Spectating

### ISSUE THREAD

**Issue by xerxes-at** [VeniceUnleashed/VeniceUnleashed#47]
Video: http://youtu.be/3fj3OXrjwh8
GFX: OC AMD HD 6670
Driver: Omega (14.12)
Can provide More Infos if necessary.

**Comment by OrfeasZ** [comment]
The 'fov glitch' is a known issue caused by the server not properly replicating roll angles when spectating a player in first person.

As for the missing HUD, we believe it's caused by the server not replicating UI state.

Finally, the floating hands issue was also present in the BF4 Beta, and we haven't really looked into it, so we're not really sure as to what's causing it.

**Comment by OrfeasZ** [comment]
Starting with build 8210, first person vehicle entry models are now being properly replicated and displayed while spectating a player.

The roll angles issue is still not resolved, and neither is the floating hands, but I will be creating separate issues for them.
