### ISSUE TITLE
[Bug] Dead bodies make footstep noises when not looking at them.

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#470]
Spooky af

**Comment by FlashHit** [comment]
That’s a vanilla bug

**Comment by 3ti65** [comment]
its a vanilla issue, probably amplified by the higher frequency
so basically, whenever you dont face a ragdoll and you're a certain distance away from it (>5m roughly), it probably does some optimization stuff in the background, because when you look back at it, the ragdoll is doing some spasmic stuff
as can be seen here:
https://imgur.com/a/LF0PWvd
this spasm sometimes causes the footsteps sounds to play, my guess thats when the ragdoll is facing the terrain in a certain angle, since it doesnt always happen

hacky fix (playing / pausing the sound every frame), just a poc, but works:
https://ybin.me/p/222619b380bf880a#z/TRToF+qtSoMHQLTHcyviFV/sG/1OLP7lx9jUY0XS4=
