### ISSUE TITLE
HUD doesn't replicate in Spectator Mode

### ISSUE THREAD

**Issue by Dendari92** [VeniceUnleashed/VeniceUnleashed#50]
The red dot in the American RDS isn't visible. Haven't tested other scopes.

**Comment by OrfeasZ** [comment]
As explained in #47 we believe this is caused by the server not replicating the client's UI state.
I've updated the issue title to more directly reflect that.

**Comment by OrfeasZ** [comment]
Starting with build 8210, most of the HUD is being replicated to spectating clients.
This includes the Vehicle HUD, the health bar, damage indicators, control point indicators, and more.

There are still a couple of things that don't properly replicate, but they are mostly minor.

Reticles are still not visible, since they are not actually a part of the HUD.
I will be creating a new issue specifically about reticles.
