### ISSUE TITLE
[Req] Add server variable that disables default loadingscreen

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#541]
Right now the vanilla loadingscreen appears for a splitsecond before the UI is loaded. This feels a bit hacky wacky. Would be good to have the possibility on the server to disable that and display a black screen instead.

**Comment by FoolHen** [comment]
That was an RM UI issue, enabling UI on extension loaded is enough to not see the vanilla UI.

**Comment by 3ti65** [comment]
No it's not @FoolHen 
If you resize the screen while loading in, you can still see the vanilla screen, as well as when the server shuts down.

**Comment by 3ti65** [comment]
I tried to remove the loading screen through EBX, with no success:

Tried removing both the UILevelDescriptionComponent from the LevelDescriptionAsset.description.components array, as well as setting the UILevelDescriptionComponent .loadingImagePath to an empty string.

Also tried to see whether there was an according UIGraphAsset being pushed through the UI:PushScreen hook, but there wasnt. The hook doesnt yield anything before the level is finished loading.

**Comment by FlashHit** [comment]
Probably you edit the wrong file:
because it is in `Levels/MP_001/MP_001/Description_Win32`
and in `Levels/MP_001/MP_001`.
The correct instance to modify the loading screen is in partition: `Levels/MP_001/MP_001/Description_Win32`.

Anyways I uploaded a mod for this right here: https://github.com/FlashHit/VU-Mods/tree/master/RemoveLoadingScreen

Note: This is one of a few partitions that are loaded on the first startup. So when you join a server it doesn't get loaded in `Partition:Loaded` (because it is already loaded), so you can straightly access and modify it.
The reason why I note that: If you modify that stuff and a player leaves the server you need to revert it, otherwise it will stay like this until the player restarts the client.

So I guess this issue can be closed.

**Comment by 3ti65** [comment]
@FlashHit was right and we were able to remove it like that. I guess that is good enough, closing this.
