### ISSUE TITLE
unable to play on servers that require DLC but I already own the DLC

### ISSUE THREAD

**Issue by GunMasterX11** [VeniceUnleashed/VeniceUnleashed#568]
I'm having an issue that for some reason isn't letting me play on certain maps because it says I don't have the map installed when Steam and Origin clearly show that I have them installed.

**Comment by OrfeasZ** [comment]
Open your start menu, type `cmd` and press enter. That should bring up the command prompt.

After it's open, type `cd "C:\Path\to\bf3"` (where `C:\Path\to\bf3` is the actual path to your Battlefield 3 installation) and press enter.

Your command prompt should then say:

> `C:\Path\to\bf3>`

If it does not and it instead shows another drive letter type `C:` (or whatever letter your drive that has BF3 in has) and press enter.

Then enter this command: `dir /b /s /a:-D > dirlisting.txt` and press enter. This should generate a file in your BF3 directory called `dirlisting.txt`. Find that file and upload it here as a reply.

**Comment by AnirohDev** [comment]
Have you installed BF3 on a drive other than C:\? 

It's already a while ago and it was BF4 instead of BF3, but I noticed that sometimes Origin installs the DLCs to the standard path on C drive (C:\Program Files (x86)\Origin Games) even tho you have selected a path on another drive (e.g. D). If this is the case, you just need to move/copy the DLC files from the standard path on C drive to your custom path on the other drive, but since you are using Steam to download and install the game, it's probably another issue. So just for the record, in case someone else has this exact problem in the future.
