### ISSUE TITLE
Permanent Lag / Rollback making the game unplayable anymore

### ISSUE THREAD

**Issue by ViPER31490** [VeniceUnleashed/VeniceUnleashed#582]
Hi there,

I just got my hands on this amazing VU and it it vorked very very well the first days without any problems at all. But since yesterday, i'm only getting lag when i begin to play, my character moves back and forth when i press W and yeah, every action i make is delayed / done and then undone (like switching from M16 to pistol, it comes back to the M16 by itself).

I tried many servers and same story everytime.

Before the issue my ping was very stable around 35ms but since it started, i'm averaging 200+ with spikes to 1k soooooo i don't understand. I'm not nerd enough to go to my in/out ports of my router, i know they exists but i don't know how to manage them if that's the problem.

It could be my connection since i recently moved but i checked, speedtested, rebooted my router and stuff but didn't change anything. My internet seems stable.

The thing is that is worked really fine the first few days and now it's not.

I put the link to the YT video from when it does it so you can see: https://youtu.be/BzXJmhgVxHE

If you guys can look into it, i'll appreciate because i reaaaaaaaaaaaally wanna play this "new" game and right now it's only frustration ahah.

Thanks <3

**Comment by OrfeasZ** [comment]
This sounds like a networking issue, possibly packet loss or something similar. Since we have not had any similar reports I can only assume that this is an issue on your end. In the video you sent, your ping also spiked to over 500ms which also seems to reinforce that. You should probably contact your ISP and tell them you have high ping in video games or something similar and see if they can help you.

**Comment by ViPER31490** [comment]
Thank you for the quick answer, i think i found the issue: it's my mom watching a movie in 1080p...... Sorry for wasting your time ahah, i didn't think about this at all
