### ISSUE TITLE
fail to connect to server after updating..

### ISSUE THREAD

**Issue by iamadeadpixel** [VeniceUnleashed/VeniceUnleashed#588]
we got message that there is a new build, we should update servers.
i did, connecting with old VU client from my machine worked like a sharm.
but after the client update aplied ,i cant connect to my local server in my network, neither to others .
servers says version 67 ....

**Comment by kiwidoggie** [comment]
@run#3492 Said this example works

```
@echo off
set INSTANCEDIRECTORY=C:\Users\Administrator\Documents\Battlefield 3\1
set IP=0.0.0.0
set GAMEPORT=25200
set RCONPORT=47200
set HARMONYPORT=7948
cd C:\Program Files (x86)\Origin Games\Battlefield 3
start vu.exe -server -dedicated -debuglog -high60 -joinhost 12.128.456.32 -listen %IP%:%GAMEPORT% -RemoteAdminPort %IP%:%RCONPORT% -mHarmonyHost %IP%:%HARMONYPORT% -serverInstancePath "%INSTANCEDIRECTORY%"
```

But omitting the -joinhost does not work, leads to a similar effect to mHarmony port being blocked (joined, quit, client kicked back to menu)

**Comment by MajorVictory** [comment]
For myself, I needed to add the launch argument `-joinhost majorvictory.no-ip.org`. This is a domain name I already had that ties to my actual ip because I host other services for myself.

I also was able to join my server hosted on my own machine and one in the same network using `-joinhost localhost` but others outside my network could not connect as I suspected it might.

Using build: #17485

**Comment by iamadeadpixel** [comment]
that did the trick !

**Comment by OrfeasZ** [comment]
This has been fixed in build `17487`. Please don't use `-joinhost` or `-joinaddr` unless you know what you're doing, as it could result in your server being unreachable for other users.
