### ISSUE TITLE
VU creates multiple processes - one for each WEBUI / Chromium

### ISSUE THREAD

**Issue by IllustrisJack** [VeniceUnleashed/VeniceUnleashed#606]
According to Kiwidog VU should only create one process, but it doesn´t. It creates a process for every single WEBUI Instance + Server Browser WEBUI appareantly stays loaded while playing on a server.

![vu](https://user-images.githubusercontent.com/76592751/107131220-cd339f80-68d4-11eb-82e4-97f6925139a9.png)

**Comment by OrfeasZ** [comment]
The behavior you're describing is expected. At startup, the VU client will have 3 processes:

1. The main VU client process, where all game logic and rendering is, basically Battlefield 3.
2. The crash reporter, which is used to submit crash reports when the client crashes.
3. A chromium renderer process for the main UI.

It will also spawn an additional chromium renderer process for every loaded mod that has a WebUI component.

**Comment by GreatApo** [comment]
That makes sense, thanks @OrfeasZ.

Jack was investigating the memory crash problem, that's why he made this question. What was found out by @IllustrisJack and xILENT was that some mods using the WebUI is probably the cause of the reported memory crashes. In more detail, xILENT noticed that whenever the scoreboard from the betterInGameAdmin was shown (hit tab), the memory of a specific process (probably of this mod) increases. This gets even worse when more people are on the server.
Now, of course that is probably a mod related problem, however, having a webUI memory limit (if possible) or something similar will probably avoid for the whole game to crash. I had a look on the mod's code, but I didn't notice anything strange right away. There is a lot of dynamic created HTML thought, thus, a memory leak problem could appear easily. When it comes to the mods, is there a way to see the WebUI code live? That will help us find the problem...

I thought you guys may want to know :)

**Comment by OrfeasZ** [comment]
You can launch the client with the `-dwebui` parameter which will let you access the Chromium dev tools from http://localhost:8884 (see [here](https://docs.veniceunleashed.net/modding/custom-ui/#debugging-your-ui)). You can then use the profiling tools in the dev tools to locate any memory issues or otherwise.

**Comment by GreatApo** [comment]
@OrfeasZ awesome, thanks! I completely missed that part of the documentation, sorry.
