### ISSUE TITLE
[Error] Player object parameter is nil in ``Player:Destroyed`` event

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#632]
```
[2021-04-28 13:55:09+02:00] [error] [VeniceEXT] [noclip] Error: [string "__init__.lua"]:68: Attempted to access a destroyed player object.
stack traceback:
    [C]: in metamethod 'index'
    [string "__init__.lua"]:68: in function <[string "__init__.lua"]:67>
```

```lua
function noclipServer:OnPlayerDeleted(p_Player)
    self.m_Soldiers[p_Player.name] = nil
end
```

**Comment by FlashHit** [comment]
If you mean the server event `Player:Destroyed` then I can confirm that.
The client event `Player:Deleted` works fine for me.

**Comment by FoolHen** [comment]
Oh yeah, its Player:Destroyed

**Comment by kiwidoggie** [comment]
This is due to the player manager changes that were made before. This is the correct intended behavior now (before it was causing a Use-After-Free which could crash the game, and did). Pending to see if this api should be changed, or 100% removed as there is no more frostbite player around to reference

**Comment by 3ti65** [comment]
All Player:Destroyed usages in RM have been replaced with Player:Left.

**Comment by FlashHit** [comment]
doesn't work for bots ^^
All bot-mods would have to dispatch the Player:Left event.

**Comment by OrfeasZ** [comment]
This should be fixed in `17656`.
