### ISSUE TITLE
[Bug] Corrupted instances on Partition:Loaded when running custom map + RM

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#633]
Repro: run maploader + RM in ``XP3_Shield ConquestLarge0 2``

Spit out errors: https://discord.com/channels/@me/578663798450421762/829806206268211252

Maploader: https://discord.com/channels/@me/578663798450421762/839509390636613642

**Comment by FoolHen** [comment]
Updated with just maploader instead of needing 2 mods (maploader+custommap). Maploader now incorporates the custom level data.

**Comment by 3ti65** [comment]
This has been mitigated by optimizing the performance of MapLoader. The issue probably still exists, but i believe kiwi spent a good amount of time debugging it to no result. If this still gets fixed, then it should be very low prio, unless it happens in other scenarios too.

**Comment by FoolHen** [comment]
I disagree, what we did is a workaround and the issue should be looked into as it may arise soon again.

**Comment by FlashHit** [comment]
oh.. might be relevant: I think that issue was because of `partition:AddInstance`, or `partition:RemoveInstance`, or both.
but not only that, any changes made to the instances will cause issues when another mod is accessing them.
So I still commented out some other OnInstanceLoaded calls in the RM mod till it stopped crashing. But it still threw errors in the maploader.
Not really sure if this is something you could fix unless there would be a priority like with hooks. So the partition gets called first in the RM mod and then (after modification) in the MapLoader mod.

**Comment by 3ti65** [comment]
I think we need a priority system similar to hooks for both events and registered callbacks. Some stuff keeps breaking irregularly when using multiple mods together that modify a similar things.

**Comment by 3ti65** [comment]
Needs a reliable repro @FlashHit

**Comment by FlashHit** [comment]
Tracked in #768. Will close this one.
