### ISSUE TITLE
Feature: Add Redis connection

### ISSUE THREAD

**Issue by Firjens** [VeniceUnleashed/VeniceUnleashed#695]
I'd like to use Redis as an alternative to the current mod.db because it's faster and has an integrated bus. However at this time there is no support for Redis.

Can Redis support be added?

**Comment by OrfeasZ** [comment]
This is a bit beyond the scope of VU. Since Redis clients talk over a relatively simple TCP protocol you should be able to re-implement the Redis protocol using the already existing TCP socket support in VU. You could also possibly take an existing redis lua library (eg. https://github.com/nrk/redis-lua) and rework it to use the VU socket implementation instead of luasocket (or whatever else it uses).

**Comment by Firjens** [comment]
> This is a bit beyond the scope of VU. Since Redis clients talk over a relatively simple TCP protocol you should be able to re-implement the Redis protocol using the already existing TCP socket support in VU. You could also possibly take an existing redis lua library (eg. https://github.com/nrk/redis-lua) and rework it to use the VU socket implementation instead of luasocket (or whatever else it uses).

Sockets will not work as it's between one client and one server and there will be multiple clients to one server.

**Comment by OrfeasZ** [comment]
I'm not sure what you mean. If you're talking about VU clients (as in the player side), then having those connect to your database is a terrible idea. If you're talking about the server-side, then I don't see how multiple VU servers wouldn't be able to connect to a single Redis instance.
