### ISSUE TITLE
[Crash] investigate lua.dll silent crashes

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#749]
All of them with Reality Mod
```
Build Number: 18060
Release Branch: dev

Crash IDs:
c1a7ef12-68e6-4707-91b6-bd4ae9c64b6b
f7a5b978-4d5b-4034-a24a-46deb7e1f7ab
4f3ccf84-24dc-4794-9cc4-02f1b7d97dd3
a64195ae-658a-4764-a6c6-808fb000c703
9f4706f1-2072-44ed-a7a0-5482bd3f0dab
a5e81122-118d-4b71-8c29-87698e5bc830
```

**Comment by FlashHit** [comment]
All of them with Battle Royale mod with custom integrated MapLoader
```
Build Number: 18060
Release Branch: dev

Crash IDs:
51422b94-45e8-4c66-bc32-7a0548784192
ed8a1c1a-f1a2-4f94-9521-79da1c3ed078
a98ce5e8-666d-4f5b-a2a6-4fe6a2abf76f
ff86b8fa-a382-40f7-ad4a-0fc73ce0838f
2c3c72b9-da97-41ea-a6a1-8df495e262d5
c7217325-15a2-4a74-b5d9-e12c1ad2a9e0
238f4d82-9df0-4ee1-a5c2-0defd2b937d2
d70b4cf2-f75e-4ebe-873d-39368fe9ae0d
216893c7-8878-419f-a490-5caab02d9adf
f8c1aa27-475b-4549-8c66-6f9297639812
eee3a63d-c4d5-4cb3-bea2-fe3954db08ff
95156edd-8643-4b32-b61a-a81d3437d7ab
```

**Comment by OrfeasZ** [comment]
| Crash ID | Possible reason |
| --------- | ----------------- |
| `c1a7ef12-68e6-4707-91b6-bd4ae9c64b6b` | `Input:PreUpdate` hook |
| `f7a5b978-4d5b-4034-a24a-46deb7e1f7ab` | Crash after `Partition:Loaded` in `Weapons/WeaponsCommon.lua:8` |
| `4f3ccf84-24dc-4794-9cc4-02f1b7d97dd3` | Possibly trying to print a recursive structure |
| `a64195ae-658a-4764-a6c6-808fb000c703` | Crash after `Partition:Loaded` in `__init__.lua:170` |
| `9f4706f1-2072-44ed-a7a0-5482bd3f0dab` | `Input:PreUpdate` hook, maybe also trying to print a recursive structure |
| `a5e81122-118d-4b71-8c29-87698e5bc830` | Crash after `Partition:Loaded` in `Vehicles/VehicleCommon.lua:44` |
| `51422b94-45e8-4c66-bc32-7a0548784192` | `Input:PreUpdate` hook |
| `ed8a1c1a-f1a2-4f94-9521-79da1c3ed078` | Possibly trying to print a recursive structure in `Logic/MapLoader.lua:36` |
| `a98ce5e8-666d-4f5b-a2a6-4fe6a2abf76f` | Same as above in `Utils/Timers.lua:112` |
| `ff86b8fa-a382-40f7-ad4a-0fc73ce0838f` | Crash after `Client:UpdateInput` in `__init__.lua:338` |
| `2c3c72b9-da97-41ea-a6a1-8df495e262d5` | Crash after `Client:UpdateInput` in `GunshipClient.lua:82` |
| `c7217325-15a2-4a74-b5d9-e12c1ad2a9e0` | Unsure, happens in `Utils/Timers.lua:112` |
| `238f4d82-9df0-4ee1-a5c2-0defd2b937d2` | Same as above |
| `d70b4cf2-f75e-4ebe-873d-39368fe9ae0d` | Possibly trying to print a recursive structure in `Logic/MapLoader.lua:38` |
| `216893c7-8878-419f-a490-5caab02d9adf` | Same as above |
| `f8c1aa27-475b-4549-8c66-6f9297639812` | Unsure, happens in `Utils/Timers.lua:112` |
| `eee3a63d-c4d5-4cb3-bea2-fe3954db08ff` | Crash after `Partition:Loaded` in `Logic/MapLoader.lua:269` |
| `95156edd-8643-4b32-b61a-a81d3437d7ab` | Unsure, happens in `Utils/Timers.lua:115` |

**Comment by 3ti65** [comment]
@OrfeasZ. We need help with this for RM Release:

1. All the crashes in Partition:Loaded are likely due to not a clear order given for different events across all mods or because we do something advanced (like adding stuff to partitions, loading bundles, etc.) and they are then causing issues in the Partition:Loaded event in either the same mod or mods run in parallel. This happens about 1/10 times when loading RM, both Server and Client. However, we don't know how to tackle or even trace down these issues, and we would require your help to trace these down.
 
2. The Input:PreUpdate crash is probably this one: https://github.com/EmulatorNexus/VeniceUnleashed/issues/724 This requires a VU fix and there's not much we can do about it.
