### ISSUE TITLE
Spread doesn't reset after ADS

### ISSUE THREAD

**Issue by nXsEagle** [VeniceUnleashed/VeniceUnleashed#81]
https://www.youtube.com/watch?v=P_XXwMAYfhQ

Would be a good idea to fix this for competitive at the very least.

**Comment by FlashHit** [comment]
```lua
local trigger = false
local hipFireTrigger = false
Events:Subscribe('WeaponFiring:Update', function(weaponFiring)

	if trigger == true and weaponFiring.gunSway ~= nil then
		weaponFiring.gunSway.dispersionAngle = 2.5 
		trigger = false
	end
	if weaponFiring.gunSway ~= nil and weaponFiring.gunSway.dispersionAngle < 2.5 then 
	
		if InputManager:IsDown(InputConceptIdentifiers.ConceptFire) and InputManager:IsDown(InputConceptIdentifiers.ConceptZoom) then
			hipFireTrigger = true
		end
		if InputManager:IsDown(InputConceptIdentifiers.ConceptFire) and InputManager:IsDown(InputConceptIdentifiers.ConceptZoom) == false and hipFireTrigger == true then
			hipFireTrigger = false
			weaponFiring.gunSway.dispersionAngle = 2.5
		end
	end
end)
Events:Subscribe('Engine:Message', function(message)
	if message.type == 638585794 then
		trigger = true
	end
end)
```
That's the fix that I figured out. I just use always `2.5` so that should be improved by getting the default value.. I tried getting it and kinda failed cuz of the modifiers. 
For example the m16 without attachments has a default value of `2.5` but if you equip the red laser pointer it gets modified `*0.5` so it's `1.25`.
I upload the file too. Maybe it gives even more information just take a look. I commented some things out etc.
[fixAimglitch.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5221097/fixAimglitch.zip)

Btw these are two fixes: 1. the euro hipfire fix https://streamable.com/8bnar1. and 2. the knife aimglitch fix https://streamable.com/3c9qd5.
