### ISSUE TITLE
every match crashes the game

### ISSUE THREAD

**Issue by NEVERTryh4rd** [VeniceUnleashed/VeniceUnleashed#819]
Crash ID: 882e1ac4-95f8-40f6-ba62-5d809d087283
Build Number: 18848
Release Branch: prod

**Comment by OrfeasZ** [comment]
Are you getting this crash on your own server or a third party server? If your own, check the mods you're running and try disabling them one by one until you find the one causing the issue. If you're playing on a third party server, you should instead ask the admin to look into their mods, since one of them is causing this.

**Comment by angelroom** [comment]
Crash ID: 0cc5da35-34d0-492a-b989-23c6c977b321
Build Number: 18848
Release Branch: prod

**Comment by thom855j** [comment]
This happens after every match no matter the map, gamemode or mods. I would put this on high priority.

**Comment by FoolHen** [comment]
@thom855j try hosting a server locally without mods, connect to it and see if it still crashes. Also make sure vanilla doesnt crash.

**Comment by FlashHit** [comment]
No proper information to this issue. We already have other issues that might fix these crashes. So I am closing this one.
