### ISSUE TITLE
Game crashing at the deploy screen (High Freq.)

### ISSUE THREAD

**Issue by neverhangover** [VeniceUnleashed/VeniceUnleashed#91]
Beta Build 8352

I was able to join a high frequency server ONCE, around 14:00 GMT+1, now, whenever I join a high frequency server , it loads the map, for a second or two the deploy menu pops up (or it doesn't even pop up) and it crashes back to the main menu.

(Yes it did restart the client when asked)

It does not seem to have any problems with regular servers.

Specs:

i3-2120
Radeon HD6850
8 GB DDR3

Windows 7 Home Premium x64

**Comment by derrod** [comment]
This is not a crash, you're kicked from the server because it's full. Unfortunately there is no message box stating the kick reason atm. and server slots are not yet configurable.

This is a measure to avoid the issues experienced when more than 20/24 players. The regular server is currently empty so that might be the reason you didn't have any issues with it.

**Comment by neverhangover** [comment]
Strange, it did have some 20-24 people on that server. 
IT DID CONNECT NOW, but the lag from high freq. (with 150) was practically unbearable.
